import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";

export const runtime = "nodejs";

const SYSTEM_PROMPT = `You are an intelligent, high-performance AI Hackathon Agent built for rapid prototyping and problem solving.
Your goal is to provide concise, structured, and highly actionable answers. 
When code or technical steps are requested, format them cleanly using standard Markdown with language identifiers.
Be helpful, analytical, creative, and clear.`;

export async function POST(req: NextRequest) {
  const startTime = Date.now();

  try {
    const body = await req.json();
    const { prompt } = body;

    if (!prompt || typeof prompt !== "string" || !prompt.trim()) {
      return NextResponse.json(
        { success: false, error: "Prompt is required and must be a non-empty string." },
        { status: 400 }
      );
    }

    const apiKey = process.env.OPENAI_API_KEY;

    // Graceful fallback for mock mode if key is missing or dummy
    if (!apiKey || apiKey === "your_key_here") {
      await new Promise((resolve) => setTimeout(resolve, 1200)); // Simulate API latency
      return NextResponse.json({
        success: true,
        isMock: true,
        output: `### 🚀 AI Hackathon Agent (Demo Mode)

Your prompt was received: **"${prompt}"**

*Note: OPENAI_API_KEY is currently set to default placeholder. Here is a sample structured response:*

1. **Analysis**: Understood requirements for quick prototype generation.
2. **Recommendation**: Configure your real key in \`.env.local\` as \`OPENAI_API_KEY=sk-...\`.
3. **Status**: System architecture and UI components are fully operational!

\`\`\`typescript
// Quick Agent Integration Test
const agentStatus = "Ready for Hackathon";
console.log({ status: agentStatus, prompt: "${prompt}" });
\`\`\`
`,
        executionTimeMs: Date.now() - startTime,
        model: "demo-mock-agent",
      });
    }

    const openai = new OpenAI({ apiKey });
    const model = process.env.OPENAI_MODEL || "gpt-4o-mini";

    const completion = await openai.chat.completions.create({
      model,
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: prompt.trim() },
      ],
      temperature: 0.7,
      max_tokens: 1500,
    });

    const output = completion.choices[0]?.message?.content || "No response generated by OpenAI API.";
    const executionTimeMs = Date.now() - startTime;

    return NextResponse.json({
      success: true,
      isMock: false,
      output,
      executionTimeMs,
      model,
      usage: completion.usage,
    });
  } catch (error: any) {
    console.error("Error in AI Agent API route:", error);
    return NextResponse.json(
      {
        success: false,
        error: error?.message || "Internal server error occurred while executing AI agent.",
      },
      { status: 500 }
    );
  }
}
